export const SEO = {
  title: "Admin Dashboard | edard3v",
  description: "Panel de administración NCS.",
  author: "edard3v",
  img: "https://res.cloudinary.com/dzuo8j1qg/image/upload/v1744800216/ncs/wqddgyinhrqpuj0vxkzv.webp",
  keywords: [
    "dashboard",
    "admin panel",
    "panel de administración",
    "edard3v",
    "edar",
    "Astro",
    "TypeScript",
    "interfaz de administración",
    "UI dashboard",
    "aplicaciones web",
    "admin dashboard astro",
    "gestión de datos",
    "admin tools",
  ],
  base_url: "https://ncs-seven.vercel.app/",
};
